-- =====================================================================================
--  create_prescription_import_phase1_tables.sql   (DRAFT — DO NOT EXECUTE THIS ROUND)
-- -------------------------------------------------------------------------------------
--  Phase 1：手動輸入 candidate + review（尚不做照片 OCR、尚不寫正式表）。
--  建立 6 張 staging / 流程表；全部與正式表分離，正式表不被本檔修改。
--
--  安全 / 規範：
--   * 僅 CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS / COMMENT。
--   * 無 DROP / DELETE / TRUNCATE、無 trigger、無 production 專用邏輯、不改既有正式表。
--   * 不含 national_id / phone / chart_no 欄位（隱私 + scope-to-schema）。
--   * 到正式表 (customers / diagnosis_codes / drug_items / drug_item_official_code_mappings
--     / prescription_nhi_drug_code_candidates) 的 FK 一律 NULLABLE + ON DELETE SET NULL，
--     不擋暫存資料保存。
--   * FK 欄位型別對齊被參照 PK：customers.id / diagnosis_codes.id = INTEGER；
--     drug_items.id / drug_item_official_code_mappings.id / prescription_nhi_drug_code_candidates.id = BIGINT。
--   * 本檔為審閱草案；實際建立前請再覆核，且建立後仍須走 dry-run / backup / verify 才寫正式表。
-- =====================================================================================

BEGIN;

-- A. prescription_import_batches ------------------------------------------------------
CREATE TABLE IF NOT EXISTS prescription_import_batches (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_source            TEXT NOT NULL
                               CHECK (import_source IN ('manual','photo_ocr','mixed')),
    batch_status             TEXT NOT NULL DEFAULT 'draft'
                               CHECK (batch_status IN ('draft','reviewing','ready_to_apply','applied','cancelled')),
    created_by_line_user_id  TEXT,
    created_by_display_name  TEXT,
    note                     TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE prescription_import_batches IS '一批處方匯入流程（manual / photo_ocr / mixed）；批次以 status 管理生命週期，不硬刪。';
CREATE INDEX IF NOT EXISTS ix_pib_status  ON prescription_import_batches (batch_status);
CREATE INDEX IF NOT EXISTS ix_pib_creator ON prescription_import_batches (created_by_line_user_id);

-- B. prescription_customer_candidates -------------------------------------------------
CREATE TABLE IF NOT EXISTS prescription_customer_candidates (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id             BIGINT NOT NULL
                           REFERENCES prescription_import_batches(id) ON DELETE RESTRICT,
    source_type          TEXT NOT NULL CHECK (source_type IN ('manual','photo_ocr')),
    source_photo_id      BIGINT,                 -- Phase 2 才加 FK → prescription_import_photos(id)
    raw_name             TEXT,
    proposed_name        TEXT,
    proposed_short_name  TEXT,
    proposed_birthday    DATE,
    proposed_gender      TEXT CHECK (proposed_gender IN ('M','F','unknown')),   -- NULL 允許
    proposed_address     TEXT,                   -- 不設 DB default「門診」，由 UI/apply 層處理
    matched_customer_id  INTEGER REFERENCES customers(id) ON DELETE SET NULL,
    match_status         TEXT NOT NULL DEFAULT 'no_match'
                           CHECK (match_status IN ('exact_match','possible_match','no_match','blocked')),
    review_status        TEXT NOT NULL DEFAULT 'pending'
                           CHECK (review_status IN ('pending','approved','edited','rejected','hold')),
    review_decision      TEXT
                           CHECK (review_decision IN ('create','link_existing','skip_existing','hold','reject')),
    confidence           TEXT CHECK (confidence IN ('high','medium','low','unknown')),
    note                 TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE prescription_customer_candidates IS '候選病人（manual/photo_ocr）；approved-only apply 才 additive 寫入 customers。無身分證/電話/病歷號欄。';
CREATE INDEX IF NOT EXISTS ix_pcc_batch        ON prescription_customer_candidates (batch_id);
CREATE INDEX IF NOT EXISTS ix_pcc_batch_review ON prescription_customer_candidates (batch_id, review_status);
CREATE INDEX IF NOT EXISTS ix_pcc_match        ON prescription_customer_candidates (match_status);
CREATE INDEX IF NOT EXISTS ix_pcc_matched_cust ON prescription_customer_candidates (matched_customer_id);

-- C. prescription_diagnosis_candidates ------------------------------------------------
CREATE TABLE IF NOT EXISTS prescription_diagnosis_candidates (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                  BIGINT NOT NULL
                                REFERENCES prescription_import_batches(id) ON DELETE RESTRICT,
    source_type               TEXT NOT NULL CHECK (source_type IN ('manual','photo_ocr')),
    source_photo_id           BIGINT,            -- Phase 2 FK
    raw_icd_code              TEXT,
    normalized_icd_code       TEXT,
    raw_diagnosis_name        TEXT,
    proposed_icd10_code       TEXT,
    proposed_name_zh          TEXT,
    proposed_name_en          TEXT,
    matched_diagnosis_code_id INTEGER REFERENCES diagnosis_codes(id) ON DELETE SET NULL,
    official_match_status     TEXT NOT NULL DEFAULT 'pending'
                                CHECK (official_match_status IN ('pending','matched','no_match','ambiguous')),
    match_status              TEXT NOT NULL DEFAULT 'no_match'
                                CHECK (match_status IN ('exact_match','possible_match','no_match','blocked')),
    review_status             TEXT NOT NULL DEFAULT 'pending'
                                CHECK (review_status IN ('pending','approved','edited','rejected','hold')),
    review_decision           TEXT
                                CHECK (review_decision IN ('create_diagnosis','link_existing','skip_existing','hold','reject')),
    confidence                TEXT CHECK (confidence IN ('high','medium','low','unknown')),
    note                      TEXT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE prescription_diagnosis_candidates IS '候選診斷碼/ICD；比對 diagnosis_codes 與 official ICD staging；approved 才寫 diagnosis_codes（link 或 additive create）。';
CREATE INDEX IF NOT EXISTS ix_pdc_batch        ON prescription_diagnosis_candidates (batch_id);
CREATE INDEX IF NOT EXISTS ix_pdc_batch_review ON prescription_diagnosis_candidates (batch_id, review_status);
CREATE INDEX IF NOT EXISTS ix_pdc_icd          ON prescription_diagnosis_candidates (normalized_icd_code);
CREATE INDEX IF NOT EXISTS ix_pdc_matched_dc   ON prescription_diagnosis_candidates (matched_diagnosis_code_id);

-- D. prescription_drug_candidates -----------------------------------------------------
CREATE TABLE IF NOT EXISTS prescription_drug_candidates (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                  BIGINT NOT NULL
                                REFERENCES prescription_import_batches(id) ON DELETE RESTRICT,
    source_type               TEXT NOT NULL CHECK (source_type IN ('manual','photo_ocr')),
    source_photo_id           BIGINT,            -- Phase 2 FK
    raw_nhi_drug_code         TEXT,
    normalized_nhi_drug_code  TEXT,
    corrected_nhi_drug_code   TEXT,
    -- effective = 人工更正 > 正規化 > 原始（STORED generated，避免漂移；要覆寫請改 corrected_）
    effective_nhi_drug_code   TEXT GENERATED ALWAYS AS
                                (COALESCE(corrected_nhi_drug_code, normalized_nhi_drug_code, raw_nhi_drug_code)) STORED,
    raw_drug_name             TEXT,
    proposed_generic_name     TEXT,
    proposed_brand_name       TEXT,
    official_drug_name_zh     TEXT,
    official_drug_name_en     TEXT,
    official_ingredient       TEXT,
    official_atc_code         TEXT,
    matched_drug_item_id      BIGINT REFERENCES drug_items(id) ON DELETE SET NULL,
    matched_official_mapping_id BIGINT REFERENCES drug_item_official_code_mappings(id) ON DELETE SET NULL,
    -- 與既有「原始健保碼抽取層」對接（沿用）：
    nhi_code_candidate_id     BIGINT REFERENCES prescription_nhi_drug_code_candidates(id) ON DELETE SET NULL,
    official_join_status      TEXT NOT NULL DEFAULT 'pending'
                                CHECK (official_join_status IN ('pending','matched','no_match','ambiguous')),
    match_status              TEXT NOT NULL DEFAULT 'no_match'
                                CHECK (match_status IN ('exact_match','possible_match','no_match','blocked')),
    review_status             TEXT NOT NULL DEFAULT 'pending'
                                CHECK (review_status IN ('pending','approved','edited','rejected','hold')),
    review_decision           TEXT
                                CHECK (review_decision IN ('link_drug_item','backfill_nhi_code','create_mapping','skip_existing','hold','reject')),
    confidence                TEXT CHECK (confidence IN ('high','medium','low','unknown')),
    note                      TEXT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE prescription_drug_candidates IS '候選藥品/健保碼；健保碼查 official_nhi_drug_payment_staging；approved 才回填 drug_items.nhi_drug_code / 建 mapping。';
CREATE INDEX IF NOT EXISTS ix_pdrc_batch        ON prescription_drug_candidates (batch_id);
CREATE INDEX IF NOT EXISTS ix_pdrc_batch_review ON prescription_drug_candidates (batch_id, review_status);
CREATE INDEX IF NOT EXISTS ix_pdrc_effcode      ON prescription_drug_candidates (effective_nhi_drug_code);
CREATE INDEX IF NOT EXISTS ix_pdrc_matched_di   ON prescription_drug_candidates (matched_drug_item_id);
CREATE INDEX IF NOT EXISTS ix_pdrc_nhi_cand     ON prescription_drug_candidates (nhi_code_candidate_id);

-- E. prescription_import_review_actions （audit trail）--------------------------------
CREATE TABLE IF NOT EXISTS prescription_import_review_actions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                 BIGINT NOT NULL
                               REFERENCES prescription_import_batches(id) ON DELETE RESTRICT,
    candidate_type           TEXT NOT NULL
                               CHECK (candidate_type IN ('customer','diagnosis','drug','link')),
    candidate_id             BIGINT,             -- polymorphic（依 candidate_type 指向對應表）；刻意不設 FK
    action                   TEXT NOT NULL
                               CHECK (action IN ('approve','edit','hold','reject','apply','rollback','create','set_decision')),
    before_json              JSONB,
    after_json               JSONB,
    reviewer_line_user_id    TEXT,
    reviewer_display_name    TEXT,
    note                     TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE prescription_import_review_actions IS '人工審核/apply/rollback 的 audit trail；candidate_id 為多型參照（無 FK），完整性由應用層維護。';
CREATE INDEX IF NOT EXISTS ix_pira_batch   ON prescription_import_review_actions (batch_id);
CREATE INDEX IF NOT EXISTS ix_pira_target  ON prescription_import_review_actions (candidate_type, candidate_id);
CREATE INDEX IF NOT EXISTS ix_pira_created ON prescription_import_review_actions (created_at);

-- F. prescription_drug_diagnosis_link_candidates （Phase 1 OPTIONAL；Phase 2 才啟用）---
CREATE TABLE IF NOT EXISTS prescription_drug_diagnosis_link_candidates (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                  BIGINT NOT NULL
                                REFERENCES prescription_import_batches(id) ON DELETE RESTRICT,
    drug_candidate_id         BIGINT REFERENCES prescription_drug_candidates(id) ON DELETE CASCADE,
    diagnosis_candidate_id    BIGINT REFERENCES prescription_diagnosis_candidates(id) ON DELETE CASCADE,
    matched_drug_item_id      BIGINT REFERENCES drug_items(id) ON DELETE SET NULL,
    matched_diagnosis_code_id INTEGER REFERENCES diagnosis_codes(id) ON DELETE SET NULL,
    source_type               TEXT NOT NULL DEFAULT 'manual'
                                CHECK (source_type IN ('same_prescription','manual')),
    link_confidence           TEXT CHECK (link_confidence IN ('high','medium','low','unknown')),
    review_status             TEXT NOT NULL DEFAULT 'pending'
                                CHECK (review_status IN ('pending','approved','edited','rejected','hold')),
    review_decision           TEXT
                                CHECK (review_decision IN ('create_link','hold','reject')),
    note                      TEXT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE prescription_drug_diagnosis_link_candidates IS 'Phase 1 OPTIONAL / Phase 2 啟用：候選藥↔診斷關聯；approved 才寫 drug_diagnosis_links。FK→candidate 用 CASCADE（derived 資料）。';
CREATE INDEX IF NOT EXISTS ix_pddlc_batch ON prescription_drug_diagnosis_link_candidates (batch_id);
CREATE INDEX IF NOT EXISTS ix_pddlc_drug  ON prescription_drug_diagnosis_link_candidates (drug_candidate_id);
CREATE INDEX IF NOT EXISTS ix_pddlc_diag  ON prescription_drug_diagnosis_link_candidates (diagnosis_candidate_id);

COMMIT;

-- 驗證（手動、唯讀，建立後可跑）：
-- SELECT table_name FROM information_schema.tables WHERE table_schema='public'
--   AND table_name LIKE 'prescription_%' ORDER BY table_name;
